### ISSUE TITLE
[Feature Request] PAC ModelBuilder - single files

### ISSUE THREAD

**Issue by AArndtDev** [microsoft/PowerPlatform-DataverseModelBuilder#10]
CrmSvcUtil generated one file for entities classes and one file for optionsets. Including those two files as symbolic links in plugin projects was more efficient than having to include hundreds of class files. The PAC ModelBuilder outputs one file for each entity and one file for each optionset. Please consider adding an option to output entities as one class file and optionsests as one class file.

**Comment by daryllabar** [comment]
The primary reason that this isn't used today is due to Visual Studio struggling with being able to parse a 200,000+ line C# file.  I don't think we would want to go back to that.  The answer is to take advantage of plugin Shared assemblies, and if you're unable to do that (might be nice to know why), I'd recommend trying shared projects.  It's been my go to for almost a decade now.

**Comment by MattB-msft** [comment]
This was a deliberate decision we made during the development of the Modelbuilder.  To @daryllabar point, the single file generation had a tendency to overwhelm VS Studio and VS Code and created challenges in source control diff management. 

We decided that it was much simpler and safer to natively split up the files into more manageable segments.
